// Re-emits tokens.css as .theme-light / .theme-dark classes so one page can show
// both themes at once. Derived, never hand-copied, so it cannot drift.
import { readFileSync, writeFileSync } from "node:fs";

const [src, out] = process.argv.slice(2);
const css = readFileSync(src, "utf8");

function block(selector) {
  const i = css.indexOf(selector);
  if (i === -1) throw new Error(`tokens.css has no ${selector} block`);
  const open = css.indexOf("{", i);
  const close = css.indexOf("}", open);
  const body = css.slice(open + 1, close);
  if (!body.includes("--")) throw new Error(`${selector} block looks empty`);
  return body.trimEnd();
}

const light = block("\n:root {");
const dark = block('\n:root[data-theme="dark"] {');

writeFileSync(
  out,
  `/* Generated by scope_tokens.mjs from tokens.css. Do not edit. */
.theme-light {${light}
}

.theme-dark {${dark}
}

.theme-light,
.theme-dark {
  background: var(--color-bg);
  color: var(--color-text);
  color-scheme: light;
}

.theme-dark {
  color-scheme: dark;
}
`,
);
console.log(`scoped tokens -> ${out}`);
